import Hero from '../components/Hero';
import Page from '../components/Page';
import TopRose from '../components/TopRose';

const Home = () => {
    return(
        <Page>
            <Hero title="Mina Rose Garden" 
                description="La rosa è un simbolo complesso, poiché racchiude  significati  contrastanti. È ambivalente, potendo significare perfezione celeste e passione terrena, tempo ed eternità, vita e morte, fecondità e verginità. Per la sua struttura a forma rotonda (in Occidente il cerchio era considerato sin dai tempi più antichi un modo per indicare la perfezione) è simbolo di completezza: rappresenta la profondità del mistero della vita, la bellezza, la grazia, la felicità, ma anche la voluttà, la passione ed è perciò, associato alla seduzione. È un fiore abbinato alle divinità femminili,  è amore, vita, creazione, bellezza e verginità; la sua rapidità nell'appassire simboleggia, al contrario, morte e sofferenza, e le sue spine evocano, invece, il sangue ed il martirio. Per affinità al cerchio, ossia ad una cosa che non ha né inizio né fine, alla rosa si associa sistematicità, di ciclicità," 
                otherText={`fenomeno che presenta anche un suo progresso temporale, un suo divenire, un suo traslare nel tempo: come una ruota di bicicletta che, dopo un giro, ritorna sì nella posizione iniziale, ma in un luogo diverso da quello precedente. La rosa è pertanto anche il simbolo del divenire e, per traslato, indica il perpetuarsi della vita umana da quella terrena verso un'altra dimensione che i credenti chiamano aldilà e che trova  il suo compimento totale nella resurrezione. È inoltre simbolo di silenzio e di riservatezza: una rosa era infatti appesa o raffigurata, nelle sale di consiglio per indicare riserbo e discrezione.Per questo motivo papa Adriano VI35 fece scolpire sui confessionali una rosa a cinque petali, simbolo del sacro vincolo della segretezza che ogni sacerdote deve mantenere nei riguardi dei penitenti che si rivolgono a lui nella confessione, e la locuzione latina "sub rosa" aveva appunto il significato di una cosa rivelata in assoluta segretezza e confidenza. La rosa d'oro denota la perfezione;quella rossa il desiderio, la passione, la gioia, la bellezza, il rapporto sessuale; è il fiore di Venere e il sangue di Adonee di Cristo.
                La rosa bianca è il fiore della luce; simboleggia l'innocenza, la verginità, lo sviluppo spirituale, il fascino.
                Bianca e rossa insieme rappresentano l'unione di fuoco ed acqua, una specie di unione degli opposti, mentre quella azzurra è il simbolo dell'impossibile.
                La rosa a quattro petali raffigura la divisione in altrettanti parti del cosmo (terra, acqua, fuoco e cielo), in altre parole gli elementi che nell'antichità alcuni filosofi consideravano primordiali e dai quali traeva origine tutto il creato. La rosa a cinque petali rappresenta invece il microcosmo.
                Nell'alchimia e nelle scienze magiche in genere, la rosa bianca e quella rossa sono ritenute gli elementi primordiali di cui si ritiene composta la materia esistente: la prima come sostanza "volatile" e la seconda come ingrediente "in combustione". Secondo questa teoria, la pluralità delle forme della materia è da attribuirsi proprio ad un diverso rapporto tra le due sostanze base.
                L'unione tra la rosa e la croce , oltre ad essere alla base della figura del rosone , è il simbolo dei Rosacroce, setta di impronta evangelica che nacque in Germania nel XVII secolo, per diffondersi successivamente in Francia. Il loro nome deriva da un adepto della setta, il cavaliere tedesco Kristian Rosenkreuz, vissuto nel secolo XV, la cui tomba venne scoperta in Marocco. I "Rosacrociani", che si vantavano di predire l'avvenire e di poter guarire malati incurabili, avevano per simbolo una rosa a cinque petali posta al centro di una croce.
                Questo emblema ricalca, peraltro, quello di Martin Lutero .Nel mondo della massoneria la rosa riveste un'importanza fondamentale; durante il funerale di un "fratello" è, infatti, costume gettare nella tomba tre rose di colore diverso, dette Rose di San Giovanni che significano amore, luce e vita. Il 24 Giugno, giorno della festività di San Giovanni è consuetudine decorare gli interni di ogni loggia massonica con tre rose di diverso colore. Anticamente i Germani eseguivano in onore della divinità Ziu (l'equivalente del dio Marte) la "Danza della spada" e al termine univano le punte delle loro spade in modo da formare una rosa.
                Sempre nella cultura tedesca la frase "Im Rosengarten sein" (Essere nel Giardino delle rose) ha un doppio ed opposto significato, uno dei quali indica l'amore casto e puro, l'altro, invece l'amore in senso passionale, biblico, che deriva da un rapporto carnale: un altro esempio della dualità che questo fiore è capace di concentrare in sé.
                Nell'iconografia cristiana viene adoperato per indicare il Paradiso.
                La rossa il sangue di Cristo.
                Viene anche usata per ricordare il Sacro Graal, ossia la Coppa che, secondo la tradizione, fu adoperata da Gesù Cristo durante l'Ultima Cena.
                Nella Bibbia come Rosa di Sharon le sue spine sono i peccati di cui la Chiesa  si è macchiata nei secoli e, più in generale, quelli di tutti i credenti, mentre la rosa senza spine è la Rosa Mistica
                Da secoli, in occasione della festa di Pentecoste, era costume far piovere sui fedeli, durante la celebrazione della Santa Messa, petali di rose per ricordare che il manifestarsi dello Spirito Santo sugli apostoli avvenne attraverso la discesa di lingue di fuoco, simili appunto a petali. Per tale ragione, la Pentecoste viene anche chiamata Pasqua delle Rose o Pasqua Rosata. Secondo il monaco Beda la tomba, dove Cristo fu collocato una volta deposto dalla croce, era dipinta di rosso e di bianco, dei due colori che, mescolati insieme, formano il rosa; anche in questo caso, come possiamo notare, c'è una perfetta commistione, una sintesi totale di due colori che rappresentano di per sé sentimenti opposti, contrastanti e la cui sintesi trova la sua più totale realizzazione proprio nel colore rosa e nel fiore. La rosa appare negli stemmi con cui sono raffigurati alcuni Santi; tra questi ricordiamo:
                S. Elisabetta d'Ungheria, S. Elisabetta del Portogallo, S. Angelo, S. Cecilia, S. Rosa da Lima e S. Rosa da Viterbo.
                Nella cultura islamica rappresenta il sangue di Maometto.Nella Rosa di Baghdad il primo cerchio rappresenta la Legge, il secondo il Cammino, il terzo la Conoscenza e tutti e tre i cerchi insieme raffigurano la Verità ed il nome di Allah.
                Nell'opera da lui scritta "Il Roseto" - in lingua originale Golestàn - l'autore definisce il giardino delle rose come il luogo dove si raggiunge il grado più alto della contemplazione.
                Nel mondo egiziano le rose erano fiori sacri alla divinità Iside, poiché rappresentavano l'amore puro del tutto liberato dall'aspetto carnale; ma è nel mondo greco-romano che il culto della rosa ha trovato maggiore sviluppo poiché  la divinità Aurora è spesso chiamata – tra gli altri da Mimnermo, poeta lirico dell'antica Grecia, vissuto tra il VII ed il VI secolo a.C. ed Omero - "La dea dalle dita di rosa" (rododaktulos), proprio perché associata al sorgere del sole. Saffo invece, dà questo attributo alla luna. Frequenti sono i riferimenti alla rosa da parte di poeti e di lirici appartenenti a varie epoche e di stili letterari diversi: dai bellicosi Omero, Mimnermo ed Alceo ai più idilliaci Ibico, Teocrito, ed Asclepiade, poeta esaltatore dell'amore. Secondo Anacreonte le rose sono profumo per gli dei e gioia per gli uomini. Nessun poeta greco, tuttavia, amò questo fiore più di Saffo; la quale predilige più d'ogni altro tutto ciò che è delicato, e paragona a questo fiore la bellezza delle fanciulle. Costei, inoltre, intitola "Le rose della Pieria" una sua composizione, volendo con questo identificare l'intera sua poesia con il suo fiore prediletto. Presso gli antichi Greci, la rosa è il simbolo della gioia, della bellezza, dell'amore e del desiderio; era il simbolo della dea Afrodite, veniva coltivata nei giardini funerari ed era spesso ornamento di tombe, per garantire al defunto il raggiungimento dell'immortalità nell'altra vita.
                Nell'alchimia e nelle scienze magiche in genere, la rosa bianca e quella rossa sono ritenute gli elementi primordiali di cui si ritiene composta la materia esistente: la prima come sostanza "volatile" e la seconda come ingrediente "in combustione". Secondo questa teoria, la pluralità delle forme della materia è da attribuirsi proprio ad un diverso rapporto tra le due sostanze base. L'unione tra la rosa e la croce , oltre ad essere alla base della figura del rosone , è il simbolo dei Rosacroce, setta di impronta evangelica che nacque in Germania nel XVII secolo, per diffondersi successivamente in Francia. Il loro nome deriva da un adepto della setta, il cavaliere tedesco Kristian Rosenkreuz, vissuto nel secolo XV, la cui tomba venne scoperta in Marocco. I "Rosacrociani", che si vantavano di predire l'avvenire e di poter guarire malati incurabili, avevano per simbolo una rosa a cinque petali posta al centro di una croce.Questo emblema ricalca, peraltro, quello di Martin Lutero .Nel mondo della massoneria la rosa riveste un'importanza fondamentale; durante il funerale di un "fratello" è, infatti, costume gettare nella tomba tre rose di colore diverso, dette Rose di San Giovanni che significano amore, luce e vita. Il 24 Giugno, giorno della festività di San Giovanni è consuetudine decorare gli interni di ogni loggia massonica con tre rose di diverso colore. Anticamente i Germani eseguivano in onore della divinità Ziu (l'equivalente del dio Marte) la "Danza della spada" e al termine univano le punte delle loro spade in modo da formare una rosa. Sempre nella cultura tedesca la frase "Im Rosengarten sein" (Essere nel Giardino delle rose) ha un doppio ed opposto significato, uno dei quali indica l'amore casto e puro, l'altro, invece l'amore in senso passionale, biblico, che deriva da un rapporto carnale: un altro esempio della dualità che questo fiore è capace di concentrare in sé. Nella novella "La Bella e la Bestia", è una semplice rosa che la bimba Belinda richiede a suo padre prima che costui inizi un lungo viaggio, mentre le due sorelle maggiori avevano preteso gioielli. È proprio per soddisfare il desiderio della figlia minore che il genitore, sulla via del ritorno, entra in un tetro palazzo al cui interno c'era un giardino pieno di rose e, certo di non essere visto, ne coglie un bocciolo provocando così l'ira della creatura mostruosa che viveva in quella dimora. E forse non è un caso che l'unica persona ad apprezzare le virtù della Bestia sia in definitiva proprio Belinda che, richiedendo per sé soltanto una rosa, aveva in definitiva dimostrato più di ogni altro di saper superare le apparenze e di andare diretta alla realtà delle cose, privilegiando la semplicità, la spontaneità e la purezza d'animo. Grazie a tutto ciò riesce a liberare la "Bestia" dal maleficio al quale era stato condannato ed a fargli assumere nuovamente le sue primitive sembianze di Principe, con il quale poi si sposerà`}
                labelButton="Vai alle offerte" link="/offerte" ></Hero>
                <TopRose limit={8}></TopRose>
        </Page>
    )
}

export default Home;